package com.veontomo.htmlvalidator

/**
 * Class for check messages generated by various checkers.
 * @param msg a message generated by a checker
 * @param status whether a check is successful or not
 */
data class CheckMessage(val msg: String, val status: Boolean)