package com.veontomo.htmlvalidator

/**
 * Class for check messages generated by various checkers.
 * For the moment, it has quite trivial implementation.
 */
class CheckMessage(val msg: String) {
    val message: String
        get() = msg
}