package com.veontomo.htmlvalidator

/**
 * Class for check messages generated by various checkers.
 * For the moment, it has quite trivial implementation.
 */
data class CheckMessage(val msg: String, val status: Boolean)